apiVersion: v1
kind: PersistentVolume

metadata:
  name: mongo-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.storage }}
  volumeMode: {{ .Values.persistentVolume.volumeMode }}
  accessModes: {{ .Values.persistentVolume.accessModes }}
  hostPath:
    path: {{ .Values.persistentVolume.path }}
