apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mongo-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: {{ .Values.persistentVolume.accessModes }}
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
