apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: mongo-nodeport-svc
  labels:
    app: mongo
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: mongo
